#!/bin/bash
cd /data1/projects/minc_helper/1.0; ./make; cd -;
option=$1

basename="surf_dist-5.1"
if [ -f $basename ]; then
    rm $basename
fi

src="$basename.c" 
lib="-L/data1/projects/minc-quarantine/install/lib/ -L/data1/projects/mycode-quarantine/5.15/lib -lmy_interpolate_sphere -lminc_helper -lbicpl  -lminc2 -lhdf5 -lnetcdf -lz -lm -ldl"
include_dir="-I/data1/projects/minc-quarantine/install/include -I./ -I/data1/projects/mycode-quarantine/5.15/include"
options="-g -O0 -std=c99 "
gcc -static $options $src -o $basename   $lib $include_dir

cp $basename /data1/projects/mycode-quarantine/5.15/bin/

if [ "$?" != "0" ]; then
    exit 1
else
    
    obj="test/GPI_2MEDA45Initial_mid_surface_right_81920.obj" 
    roi="test/infarct_surface.txt" 
    dist="test/distance_map.txt"
    arguments="$obj $roi $dist"
    command="./$basename  $arguments"
    echo $command
    if [ "$option" == "-gdb" ]; then
        gdb --args $command
    elif [ "$option" == "-valgrind" ]; then
       valgrind --tool=memcheck --leak-check=yes  --leak-check=full $command
    else    
        time $command
        brain-view.sh $obj $dist
    fi
fi
