#!/bin/bash
option=$1
cd /data1/projects/minc_helper/1.0; ./make; cd -;
basename="minc_integrate-1.0"

if [ -f $basename ]; then
    rm $basename
fi

src="${basename}.c"
options="-g -pthread -static -O0 -ffast-math  -std=c99 -fopenmp "
lib_dir="-L/data1/projects/minc-quarantine/install/lib/ -L/data1/projects/mycode-quarantine/5.15/lib"
lib="-lminc_helper -lminc2 -lhdf5 -lnetcdf -lm -lz -ldl"
include_dir="-I./ -I/data1/projects/minc-quarantine/install/include/ -I/data1/projects/mycode-quarantine/5.15/include/"

echo $src
gcc  $options  $src -o $basename $include_dir $lib_dir $lib ;


if [ "$?" != "0" ]; then
    exit 1
else
    cp $basename /data1/projects/mycode-quarantine/5.15/bin/
    ln -fs /data1/projects/mycode-quarantine/5.15/bin/${basename}  /data1/projects/mycode-quarantine/5.15/bin/anisotropic_diffusion
    image="/data1/projects/bigbrain/image-based_simulation/tac.mnc" #"/data1/projects/bigbrain/occipital/segmentation/final_v1/complete/layers_v2_rsl.mnc"   # image.mnc
    new_step_size=1
    output="layers_1mm.mnc"
    command="${basename} $image $new_step_size $output"  
    echo $command
    if [ "$option" == "-gdb" ]; then
         gdb --args $command
    elif [ "$option" == "-valgrind" ]; then
       valgrind --tool=memcheck --leak-check=yes  --leak-check=full $command
    elif [ "$option" == "-test" ]; then
        echo Nothing set
    else   
        time $command
    fi
 
fi




